/* O projeto só funciona se inicializado pela Home*/
package visao;

import controle.ControleDep;
import controle.ControleFunc;
import modelo.ManterDep;
import modelo.ManterFunc;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Pattern;
import javax.swing.text.AttributeSet;
import javax.swing.text.BadLocationException;
import javax.swing.text.PlainDocument;

public class AltFunc extends javax.swing.JFrame {

    private String nome;
    private int idade;
    private String cargo;
    private String CPF;
    private String email;
    private String formacao;
    private double remuneracao;
    private String nomeDepartamento;
    private int departamento_id;

    /**
     * Creates new form AltFunc
     */
    public AltFunc(String nome, int idade, String cargo, String CPF, String email, String formacao, double remuneracao, String nomeDepartamento, int departamento_id) {
        initComponents();
        iniciando();
        this.nome = nome;
        this.idade = idade;
        this.cargo = cargo;
        this.CPF = CPF;
        this.email = email;
        this.formacao = formacao;
        this.remuneracao = remuneracao;
        this.nomeDepartamento = nomeDepartamento;
        this.departamento_id = departamento_id;

        DefaultTableModel model = (DefaultTableModel) jTlistarfunc2.getModel();
        model.setRowCount(0);
        model.addRow(new Object[]{CPF, nome, remuneracao, departamento_id});

        jTnovodepartamentofunc.setText(nomeDepartamento);
        jTnovoemail.setText(email);
        jTnovoidade.setText(String.valueOf(idade));
        jTformacao.setText(formacao);
        jTcargo.setText(cargo);

    }

    private AltFunc() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    private void iniciando() {

        jTnovoidade.setDocument(new PlainDocument() {
            @Override
            public void insertString(int offset, String str, AttributeSet attr) throws BadLocationException {
                if (str == null) {
                    return;
                }
                if ((getLength() + str.length()) <= 2 && str.matches("\\d*")) {
                    super.insertString(offset, str, attr);
                }
            }
        });
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bGcargo = new javax.swing.ButtonGroup();
        bGformacao = new javax.swing.ButtonGroup();
        jLabel14 = new javax.swing.JLabel();
        jBlimpar4 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jBatualizarF2 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jTnovodepartamentofunc = new javax.swing.JTextField();
        jTnovoidade = new javax.swing.JTextField();
        jRmedio = new javax.swing.JRadioButton();
        jRsuperior = new javax.swing.JRadioButton();
        jRpos = new javax.swing.JRadioButton();
        jRmestrado = new javax.swing.JRadioButton();
        jRdoutorado = new javax.swing.JRadioButton();
        jRaprendiz = new javax.swing.JRadioButton();
        jRestagio = new javax.swing.JRadioButton();
        jRjunior = new javax.swing.JRadioButton();
        jRpleno = new javax.swing.JRadioButton();
        jTextField7 = new javax.swing.JTextField();
        jRsenior = new javax.swing.JRadioButton();
        jBhome6 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTlistarfunc2 = new javax.swing.JTable();
        jTnovoemail = new javax.swing.JTextField();
        jTcargo = new javax.swing.JTextField();
        jTformacao = new javax.swing.JTextField();
        jBvoltar2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel14.setText("Idade:");

        jBlimpar4.setBackground(new java.awt.Color(153, 153, 153));
        jBlimpar4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jBlimpar4.setText("Limpar");
        jBlimpar4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBlimpar4ActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel16.setText("Cargo:");

        jBatualizarF2.setBackground(new java.awt.Color(153, 153, 153));
        jBatualizarF2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jBatualizarF2.setText("Atualizar");
        jBatualizarF2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBatualizarF2ActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel15.setText("Formação:");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setText("Departamento:");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel13.setText("Email:");

        jTnovodepartamentofunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTnovodepartamentofuncActionPerformed(evt);
            }
        });

        bGformacao.add(jRmedio);
        jRmedio.setText("Ensino Médio");

        bGformacao.add(jRsuperior);
        jRsuperior.setText("Ensino Superior");

        bGformacao.add(jRpos);
        jRpos.setText("Pós-Graduação");

        bGformacao.add(jRmestrado);
        jRmestrado.setText("Mestrado");

        bGformacao.add(jRdoutorado);
        jRdoutorado.setText("Doutorado");

        bGcargo.add(jRaprendiz);
        jRaprendiz.setText("Menor Aprendiz");

        bGcargo.add(jRestagio);
        jRestagio.setText("Estagiário");

        bGcargo.add(jRjunior);
        jRjunior.setText("Desenvolvedor Júnior");

        bGcargo.add(jRpleno);
        jRpleno.setText("Desenvolvedor Pleno");

        jTextField7.setEditable(false);
        jTextField7.setBackground(new java.awt.Color(0, 0, 0));
        jTextField7.setFont(new java.awt.Font("Segoe UI Black", 3, 24)); // NOI18N
        jTextField7.setForeground(new java.awt.Color(255, 255, 255));
        jTextField7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField7.setText("   JDEVS.UPDATEFuncionário() ");

        bGcargo.add(jRsenior);
        jRsenior.setText("Desenvolvedor Sênior");

        jBhome6.setBackground(new java.awt.Color(153, 153, 153));
        jBhome6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jBhome6.setText("Home");
        jBhome6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBhome6ActionPerformed(evt);
            }
        });

        jTlistarfunc2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CPF", "Nome", "Remuneração", "Departamento_id"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTlistarfunc2);
        if (jTlistarfunc2.getColumnModel().getColumnCount() > 0) {
            jTlistarfunc2.getColumnModel().getColumn(3).setMinWidth(0);
            jTlistarfunc2.getColumnModel().getColumn(3).setPreferredWidth(0);
            jTlistarfunc2.getColumnModel().getColumn(3).setMaxWidth(0);
        }

        jTcargo.setEditable(false);

        jTformacao.setEditable(false);

        jBvoltar2.setBackground(new java.awt.Color(153, 153, 153));
        jBvoltar2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jBvoltar2.setText("Voltar");
        jBvoltar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBvoltar2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTextField7)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jRmestrado, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jRdoutorado, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jRmedio, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(7, 7, 7))
                                .addComponent(jRpos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jRsuperior, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTformacao, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jBvoltar2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBhome6)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(83, 83, 83)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRaprendiz)
                                    .addComponent(jRjunior)
                                    .addComponent(jRpleno)
                                    .addComponent(jRsenior)
                                    .addComponent(jRestagio, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTcargo, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)))
                                .addGap(217, 217, 217))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jBatualizarF2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBlimpar4)
                                .addContainerGap())))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTnovoidade, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTnovoemail, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTnovodepartamentofunc, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(208, 208, 208))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jTnovodepartamentofunc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jTnovoemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTnovoidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(jTformacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRmedio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRsuperior)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRpos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRmestrado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRdoutorado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jBatualizarF2)
                            .addComponent(jBhome6)
                            .addComponent(jBlimpar4)
                            .addComponent(jBvoltar2)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(jTcargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRaprendiz)
                        .addGap(8, 8, 8)
                        .addComponent(jRestagio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRjunior)
                        .addGap(12, 12, 12)
                        .addComponent(jRpleno)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRsenior, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBlimpar4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBlimpar4ActionPerformed
        // TODO add your handling code here:
        jTnovodepartamentofunc.setText(nomeDepartamento);
        jTnovoemail.setText(email);
        jTnovoidade.setText(String.valueOf(idade));
        bGformacao.clearSelection();
        bGcargo.clearSelection();
        jTnovodepartamentofunc.requestFocus();

    }//GEN-LAST:event_jBlimpar4ActionPerformed

    private void jBatualizarF2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBatualizarF2ActionPerformed
        // TODO add your handling code here:
        ArrayList<String> erros4 = new ArrayList<>();
        try {
            String novoDep = jTnovodepartamentofunc.getText();
            String novoEmail = jTnovoemail.getText();
            String novoIdadeStr = jTnovoidade.getText();
            String novoFormacao = jTformacao.getText();
            String novoCargo = jTcargo.getText();
            int novoIdade = 0;

            if (novoDep.isEmpty()) {
                erros4.add("O campo Departamento não pode estar vazio!");
                jTnovodepartamentofunc.requestFocus();
            } else if (!Pattern.matches("^[\\p{L} ]+$", novoDep)) {
                erros4.add("O campo Departamento deve conter apenas letras1");
                jTnovodepartamentofunc.requestFocus();
            } else {
                ManterDep md = new ManterDep();
                ArrayList<ControleDep> depLista = md.PesquisarDepNome(novoDep);

                if (depLista.isEmpty()) {
                    erros4.add("Departamento não encontrado!");
                    JOptionPane.showMessageDialog(this, "Departamento não encontrado.", "Erro", JOptionPane.ERROR_MESSAGE);
                    return;
                } else {
                    departamento_id = depLista.get(0).getId();
                }
            }

            if (novoEmail.isEmpty()) {
                erros4.add("O campo Email não pode estar vazio!");
                jTnovoemail.requestFocus();
            } else if (!Pattern.matches("^[\\w-\\.]+@([\\w-]+\\.)+[\\w-]{2,4}$", novoEmail)) {
                erros4.add("O campo Email deve conter um email válido!");
                jTnovoemail.requestFocus();
            }

            if (novoIdadeStr.isEmpty()) {
                erros4.add("O campo Idade não pode estar vazio!");
                jTnovoidade.requestFocus();
            } else {
                try {
                    novoIdade = Integer.parseInt(novoIdadeStr);
                    if (novoIdade < 14 || novoIdade > 80) {
                        erros4.add("O campo Idade deve ser um número de 14 a 80!");
                        jTnovoidade.requestFocus();
                    }
                } catch (NumberFormatException e) {
                    erros4.add("O campo Idade deve ser um número inteiro positivo!");
                    jTnovoidade.requestFocus();
                }
            }

            if (!jRmedio.isSelected() && !jRsuperior.isSelected() && !jRpos.isSelected()
                    && !jRmestrado.isSelected() && !jRdoutorado.isSelected()) {
                erros4.add("Escolha uma formação!");
            } else {
                if (jRmedio.isSelected()) {
                    novoFormacao = "medio";
                } else if (jRsuperior.isSelected()) {
                    novoFormacao = "superior";
                } else if (jRpos.isSelected()) {
                    novoFormacao = "pos";
                } else if (jRmestrado.isSelected()) {
                    novoFormacao = "mestrado";
                } else if (jRdoutorado.isSelected()) {
                    novoFormacao = "doutorado";
                }
            }

            if (!jRaprendiz.isSelected() && !jRestagio.isSelected() && !jRjunior.isSelected()
                    && !jRpleno.isSelected() && !jRsenior.isSelected()) {
                erros4.add("Escolha um cargo!");
            } else {
                if (jRaprendiz.isSelected()) {
                    novoCargo = "aprendiz";
                } else if (jRestagio.isSelected()) {
                    novoCargo = "estagio";
                } else if (jRjunior.isSelected()) {
                    novoCargo = "junior";
                } else if (jRpleno.isSelected()) {
                    novoCargo = "pleno";
                } else if (jRsenior.isSelected()) {
                    novoCargo = "senior";
                }
            }

            if (!erros4.isEmpty()) {
                StringBuilder mensagem = new StringBuilder("Erros encontrados:\n");
                for (String erro : erros4) {
                    mensagem.append(erro).append("\n");
                }
                JOptionPane.showMessageDialog(this, mensagem.toString(), "Erro de Validação", JOptionPane.ERROR_MESSAGE);
                return;
            }

            ControleFunc func = new ControleFunc();
            func.setCPF(this.CPF);
            func.setNome(nome);
            func.setIdade(novoIdade);
            func.setCargo(novoCargo);
            func.setEmail(novoEmail);
            func.setFormacao(novoFormacao);
            func.setRemuneracao(remuneracao);
            func.setDepartamento_id(departamento_id);

            ManterFunc dao = new ManterFunc();
            boolean atualizacao = dao.atualizarFunc(func);

            if (atualizacao) {
                new ListarFunc("acessoPermitido").setVisible(true);
                this.dispose();
            }
        } catch (Exception e) {
            Logger.getLogger(AltFunc.class.getName()).log(Level.SEVERE, null, e);
        }


    }//GEN-LAST:event_jBatualizarF2ActionPerformed

    private void jTnovodepartamentofuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTnovodepartamentofuncActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTnovodepartamentofuncActionPerformed

    private void jBhome6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBhome6ActionPerformed
        // TODO add your handling code here:
        Home home = new Home();
        home.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jBhome6ActionPerformed

    private void jBvoltar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBvoltar2ActionPerformed
        // TODO add your handling code here:
        ListarFunc lf = new ListarFunc("acessoPermitido");
        lf.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jBvoltar2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AltFunc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AltFunc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AltFunc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AltFunc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AltFunc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bGcargo;
    private javax.swing.ButtonGroup bGformacao;
    private javax.swing.JButton jBatualizarF2;
    private javax.swing.JButton jBhome6;
    private javax.swing.JButton jBlimpar4;
    private javax.swing.JButton jBvoltar2;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JRadioButton jRaprendiz;
    private javax.swing.JRadioButton jRdoutorado;
    private javax.swing.JRadioButton jRestagio;
    private javax.swing.JRadioButton jRjunior;
    private javax.swing.JRadioButton jRmedio;
    private javax.swing.JRadioButton jRmestrado;
    private javax.swing.JRadioButton jRpleno;
    private javax.swing.JRadioButton jRpos;
    private javax.swing.JRadioButton jRsenior;
    private javax.swing.JRadioButton jRsuperior;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTcargo;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTformacao;
    private javax.swing.JTable jTlistarfunc2;
    private javax.swing.JTextField jTnovodepartamentofunc;
    private javax.swing.JTextField jTnovoemail;
    private javax.swing.JTextField jTnovoidade;
    // End of variables declaration//GEN-END:variables
}
