/* O projeto só funciona se inicializado pela Home*/
package visao;

import controle.ControleDep;
import controle.ControleFunc;
import modelo.ManterDep;
import modelo.ManterFunc;
import java.util.ArrayList;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.text.AttributeSet;
import javax.swing.text.BadLocationException;
import javax.swing.text.PlainDocument;


public class CadFunc extends javax.swing.JFrame {

    /**
     * Creates new form CadFunc
     */
    public CadFunc(String parametro) {
        if (!"acessoPermitido".equals(parametro)) {
            JOptionPane.showMessageDialog(null, "Acesso negado. Navegue através da Home.", "Erro de Acesso", JOptionPane.ERROR_MESSAGE);
            System.exit(0); 
        }
        initComponents();
        iniciando();
    }

    private CadFunc() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    private void iniciando() {

        jTcpf.setDocument(new PlainDocument() {
            @Override
            public void insertString(int offset, String str, AttributeSet attr) throws BadLocationException {
                if (str == null) {
                    return;
                }
                if ((getLength() + str.length()) <= 11 && str.matches("\\d*")) {
                    super.insertString(offset, str, attr);
                }
            }
        });

        jTidade.setDocument(new PlainDocument() {
            @Override
            public void insertString(int offset, String str, AttributeSet attr) throws BadLocationException {
                if (str == null) {
                    return;
                }
                if ((getLength() + str.length()) <= 2 && str.matches("\\d*")) {
                    super.insertString(offset, str, attr);
                }
            }
        });
    }


    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupformacao = new javax.swing.ButtonGroup();
        buttonGroupcargo = new javax.swing.ButtonGroup();
        jTextField5 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTnomefunc = new javax.swing.JTextField();
        jTcpf = new javax.swing.JTextField();
        jTemail = new javax.swing.JTextField();
        jTnomedepF = new javax.swing.JTextField();
        jTidade = new javax.swing.JTextField();
        jRmedio = new javax.swing.JRadioButton();
        jRsuperior = new javax.swing.JRadioButton();
        jRpos = new javax.swing.JRadioButton();
        jRmestrado = new javax.swing.JRadioButton();
        jRdoutorado = new javax.swing.JRadioButton();
        jRaprendiz = new javax.swing.JRadioButton();
        jRestagio = new javax.swing.JRadioButton();
        jRjunior = new javax.swing.JRadioButton();
        jRpleno = new javax.swing.JRadioButton();
        jRsenior = new javax.swing.JRadioButton();
        jBhome4 = new javax.swing.JButton();
        jBlimpar3 = new javax.swing.JButton();
        jBcadastrarF = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextField5.setEditable(false);
        jTextField5.setBackground(new java.awt.Color(0, 0, 0));
        jTextField5.setFont(new java.awt.Font("Segoe UI Black", 3, 24)); // NOI18N
        jTextField5.setForeground(new java.awt.Color(255, 255, 255));
        jTextField5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField5.setText("        JDEVS.setFuncionário() ");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Nome:");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("Idade:");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setText("Cargo:");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setText("Formação:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Departamento:");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("CPF:");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Email:");

        jTcpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTcpfActionPerformed(evt);
            }
        });

        jTemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTemailActionPerformed(evt);
            }
        });

        buttonGroupformacao.add(jRmedio);
        jRmedio.setText("Ensino Médio");

        buttonGroupformacao.add(jRsuperior);
        jRsuperior.setText("Ensino Superior");

        buttonGroupformacao.add(jRpos);
        jRpos.setText("Pós-Graduação");

        buttonGroupformacao.add(jRmestrado);
        jRmestrado.setText("Mestrado");

        buttonGroupformacao.add(jRdoutorado);
        jRdoutorado.setText("Doutorado");

        buttonGroupcargo.add(jRaprendiz);
        jRaprendiz.setText("Menor Aprendiz");

        buttonGroupcargo.add(jRestagio);
        jRestagio.setText("Estagiário");

        buttonGroupcargo.add(jRjunior);
        jRjunior.setText("Desenvolvedor Júnior");

        buttonGroupcargo.add(jRpleno);
        jRpleno.setText("Desenvolvedor Pleno");

        buttonGroupcargo.add(jRsenior);
        jRsenior.setText("Desenvolvedor Sênior");

        jBhome4.setBackground(new java.awt.Color(153, 153, 153));
        jBhome4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jBhome4.setText("Home");
        jBhome4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBhome4ActionPerformed(evt);
            }
        });

        jBlimpar3.setBackground(new java.awt.Color(153, 153, 153));
        jBlimpar3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jBlimpar3.setText("Limpar");
        jBlimpar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBlimpar3ActionPerformed(evt);
            }
        });

        jBcadastrarF.setBackground(new java.awt.Color(153, 153, 153));
        jBcadastrarF.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jBcadastrarF.setText("Cadastrar");
        jBcadastrarF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBcadastrarFActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTemail, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(214, 214, 214))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTidade, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTcpf, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTnomefunc, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTnomedepF, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(78, Short.MAX_VALUE))))
            .addComponent(jTextField5)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(84, 84, 84)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jRmestrado, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jRdoutorado, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jRmedio, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(116, 116, 116))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jRpos, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jRsuperior))
                        .addGap(109, 109, 109)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRaprendiz))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRjunior)
                            .addComponent(jRpleno)
                            .addComponent(jRsenior)
                            .addComponent(jRestagio, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jBhome4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBcadastrarF)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBlimpar3)
                .addGap(15, 15, 15))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTnomefunc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTnomedepF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTcpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRmedio)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRsuperior)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRpos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRmestrado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRdoutorado))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(jRaprendiz))
                        .addGap(8, 8, 8)
                        .addComponent(jRestagio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRjunior)
                        .addGap(12, 12, 12)
                        .addComponent(jRpleno)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRsenior, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBcadastrarF)
                    .addComponent(jBhome4)
                    .addComponent(jBlimpar3))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTemailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTemailActionPerformed

    private void jBlimpar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBlimpar3ActionPerformed
        // TODO add your handling code here:
        jTnomefunc.setText("");
        jTidade.setText("");
        jTcpf.setText("");
        jTemail.setText("");
        jTnomedepF.setText("");
        buttonGroupformacao.clearSelection();
        buttonGroupcargo.clearSelection();
        jTnomefunc.requestFocus();

    }//GEN-LAST:event_jBlimpar3ActionPerformed

    private void jBcadastrarFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBcadastrarFActionPerformed
        // TODO add your handling code here:
        ArrayList<String> erros3 = new ArrayList<>();
        int departamento_id = -1;

        try {
            String nome = jTnomefunc.getText();
            String email = jTemail.getText();
            String CPF = jTcpf.getText();
            String idadeStr = jTidade.getText();
            String nomedepF = jTnomedepF.getText();
            int idade;
            String formacao = "";
            String cargo = "";

            if (nome.isEmpty()) {
                erros3.add("O campo Nome não pode estar vazio!");
                jTnomefunc.requestFocus();
            } else if (!Pattern.matches("^[\\p{L} ]+$", nome)) {
                erros3.add("O campo Nome deve conter apenas letras!");
                jTnomefunc.requestFocus();
            }

            if (nomedepF.isEmpty()) {
                erros3.add("O campo Departamento não pode estar vazio!");
                jTnomedepF.requestFocus();
            } else if (!Pattern.matches("^[\\p{L} ]+$", nomedepF)) {
                erros3.add("O campo Departamento deve conter apenas letras!");
                jTnomedepF.requestFocus();
            } else {
                ManterDep md = new ManterDep();
                ArrayList<ControleDep> depLista = md.PesquisarDepNome(nomedepF);

                if (depLista.isEmpty()) {
                    erros3.add("Departamento não encontrado!");
                    JOptionPane.showMessageDialog(this, "Departamento não encontrado.", "Erro", JOptionPane.ERROR_MESSAGE);
                    return;
                } else {
                    departamento_id = depLista.get(0).getId();
                }
            }

            if (email.isEmpty()) {
                erros3.add("O campo Email não pode estar vazio!");
                jTemail.requestFocus();
            } else if (!Pattern.matches("^[\\w-\\.]+@([\\w-]+\\.)+[\\w-]{2,4}$", email)) {
                erros3.add("O campo Email deve conter um email válido!");
                jTemail.requestFocus();
            }

            if (CPF.isEmpty()) {
                erros3.add("O campo CPF não pode estar vazio!");
                jTcpf.requestFocus();
            } else if (CPF.length() != 11 || !CPF.matches("\\d{11}")) {
                erros3.add("O campo CPF deve conter exatamente 11 dígitos numéricos!");
                jTcpf.requestFocus();
            }

            if (idadeStr.isEmpty()) {
                erros3.add("O campo Idade não pode estar vazio!");
                jTidade.requestFocus();
            } else {
                try {
                    idade = Integer.parseInt(idadeStr);
                    if (idade < 14 || idade > 80) {
                        erros3.add("O campo Idade deve ser um número de 14 a 80!");
                        jTidade.requestFocus();
                    }
                } catch (NumberFormatException e) {
                    erros3.add("O campo Idade deve ser um número inteiro positivo!");
                    jTidade.requestFocus();
                }
            }

            if (!jRmedio.isSelected() && !jRsuperior.isSelected() && !jRpos.isSelected()
                    && !jRmestrado.isSelected() && !jRdoutorado.isSelected()) {
                erros3.add("Escolha uma formação!");
            } else {
                if (jRmedio.isSelected()) {
                    formacao = "medio";
                } else if (jRsuperior.isSelected()) {
                    formacao = "superior";
                } else if (jRpos.isSelected()) {
                    formacao = "pos";
                } else if (jRmestrado.isSelected()) {
                    formacao = "mestrado";
                } else if (jRdoutorado.isSelected()) {
                    formacao = "doutorado";
                }
            }

            if (!jRaprendiz.isSelected() && !jRestagio.isSelected() && !jRjunior.isSelected()
                    && !jRpleno.isSelected() && !jRsenior.isSelected()) {
                erros3.add("Escolha um cargo!");
            } else {
                if (jRaprendiz.isSelected()) {
                    cargo = "aprendiz";
                } else if (jRestagio.isSelected()) {
                    cargo = "estagio";
                } else if (jRjunior.isSelected()) {
                    cargo = "junior";
                } else if (jRpleno.isSelected()) {
                    cargo = "pleno";
                } else if (jRsenior.isSelected()) {
                    cargo = "senior";
                }
            }

            if (!erros3.isEmpty()) {
                StringBuilder mensagem = new StringBuilder("Erros encontrados:\n");
                for (String erro : erros3) {
                    mensagem.append(erro).append("\n");
                }
                JOptionPane.showMessageDialog(this, mensagem.toString(), "Erro de Validação", JOptionPane.ERROR_MESSAGE);
                return;
            }

            ControleFunc cf = new ControleFunc();
            cf.setNome(nome);
            cf.setIdade(Integer.parseInt(idadeStr));
            cf.setCargo(cargo);
            cf.setCPF(CPF);
            cf.setEmail(email);
            cf.setFormacao(formacao);
            cf.setDepartamento_id(departamento_id);
            double remuneracao = 0;
            cf.setRemuneracao(remuneracao);

            ManterFunc mf = new ManterFunc();
            mf.inserirF(cf);
            jTnomefunc.setText("");
            jTidade.setText("");
            jTcpf.setText("");
            jTemail.setText("");
            jTnomedepF.setText("");
            buttonGroupformacao.clearSelection();
            buttonGroupcargo.clearSelection();

        } catch (Exception ex) {
            Logger.getLogger(CadFunc.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_jBcadastrarFActionPerformed

    private void jTcpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTcpfActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jTcpfActionPerformed

    private void jBhome4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBhome4ActionPerformed
        // TODO add your handling code here:
        Home home = new Home();
        home.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jBhome4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadFunc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadFunc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadFunc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadFunc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadFunc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupcargo;
    private javax.swing.ButtonGroup buttonGroupformacao;
    private javax.swing.JButton jBcadastrarF;
    private javax.swing.JButton jBhome4;
    private javax.swing.JButton jBlimpar3;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRaprendiz;
    private javax.swing.JRadioButton jRdoutorado;
    private javax.swing.JRadioButton jRestagio;
    private javax.swing.JRadioButton jRjunior;
    private javax.swing.JRadioButton jRmedio;
    private javax.swing.JRadioButton jRmestrado;
    private javax.swing.JRadioButton jRpleno;
    private javax.swing.JRadioButton jRpos;
    private javax.swing.JRadioButton jRsenior;
    private javax.swing.JRadioButton jRsuperior;
    private javax.swing.JTextField jTcpf;
    private javax.swing.JTextField jTemail;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTidade;
    private javax.swing.JTextField jTnomedepF;
    private javax.swing.JTextField jTnomefunc;
    // End of variables declaration//GEN-END:variables
}
