/* O projeto só funciona se inicializado pela Home*/
package visao;

import controle.ControleDep;
import modelo.ManterDep;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

public class ListarDep extends javax.swing.JFrame {

    /**
     * Creates new form ListarDep
     */
    public ListarDep(String parametro) {
        if (!"acessoPermitido".equals(parametro)) {
            JOptionPane.showMessageDialog(null, "Acesso negado. Navegue através da Home.", "Erro de Acesso", JOptionPane.ERROR_MESSAGE);
            System.exit(0); 
        }
        initComponents();
    }


    ListarDep() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    private void verificarAcesso(String parametro) {
        if (!"acessoPermitido".equals(parametro)) {
            JOptionPane.showMessageDialog(null, "Acesso negado. Navegue através da Home.", "Erro de Acesso", JOptionPane.ERROR_MESSAGE);
            this.dispose();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField3 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTlistardep = new javax.swing.JTable();
        jBdeletardep = new javax.swing.JButton();
        jBimprimirdep = new javax.swing.JButton();
        jBatualizardep = new javax.swing.JButton();
        jBhome2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextField3.setEditable(false);
        jTextField3.setBackground(new java.awt.Color(0, 0, 0));
        jTextField3.setFont(new java.awt.Font("Segoe UI Black", 3, 24)); // NOI18N
        jTextField3.setForeground(new java.awt.Color(255, 255, 255));
        jTextField3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField3.setText("    JDEVS.getDepartamentos() ");

        jTlistardep.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nome", "Andar"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTlistardep);
        if (jTlistardep.getColumnModel().getColumnCount() > 0) {
            jTlistardep.getColumnModel().getColumn(0).setMinWidth(0);
            jTlistardep.getColumnModel().getColumn(0).setPreferredWidth(0);
            jTlistardep.getColumnModel().getColumn(0).setMaxWidth(0);
        }

        jBdeletardep.setBackground(new java.awt.Color(153, 153, 153));
        jBdeletardep.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jBdeletardep.setText("Deletar");
        jBdeletardep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBdeletardepActionPerformed(evt);
            }
        });

        jBimprimirdep.setBackground(new java.awt.Color(153, 153, 153));
        jBimprimirdep.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jBimprimirdep.setText("Imprimir");
        jBimprimirdep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBimprimirdepActionPerformed(evt);
            }
        });

        jBatualizardep.setBackground(new java.awt.Color(153, 153, 153));
        jBatualizardep.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jBatualizardep.setText("Atualizar");
        jBatualizardep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBatualizardepActionPerformed(evt);
            }
        });

        jBhome2.setBackground(new java.awt.Color(153, 153, 153));
        jBhome2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jBhome2.setText("Home");
        jBhome2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBhome2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jBhome2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBimprimirdep)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBdeletardep)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBatualizardep)
                .addGap(3, 3, 3))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBdeletardep)
                    .addComponent(jBimprimirdep)
                    .addComponent(jBatualizardep)
                    .addComponent(jBhome2))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBdeletardepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBdeletardepActionPerformed
        // TODO add your handling code here:
        try {
            int linhaSelecionada = jTlistardep.getSelectedRow();
            if (linhaSelecionada != -1) {
                int id = (int) jTlistardep.getValueAt(linhaSelecionada, 0);
                ControleDep cd = new ControleDep();
                cd.setId(id);
                ManterDep depdao = new ManterDep();

                depdao.deletarDep(cd);

                jBimprimirdepActionPerformed(null);
            } else {
                JOptionPane.showMessageDialog(this, "Selecione uma linha para deletar!");
            }
        } catch (Exception ex) {
            Logger.getLogger(ListarDep.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jBdeletardepActionPerformed

    private void jBimprimirdepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBimprimirdepActionPerformed
        // TODO add your handling code here:
        try {
            ManterDep md = new ManterDep();
            DefaultTableModel modeloTabela = (DefaultTableModel) jTlistardep.getModel();
            ArrayList<ControleDep> departamentos = md.PesquisarTudoD();
            modeloTabela.setRowCount(0);
            if (departamentos.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Nenhum Departamento Encontrado!");
            } else {
                for (ControleDep cd : departamentos) {
                    modeloTabela.addRow(new Object[]{cd.getId(), cd.getNome(), cd.getAndar()});
                }
            }
        } catch (Exception ex) {
            Logger.getLogger(ListarDep.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Erro ao Listar Departamentos!");
        }

    }//GEN-LAST:event_jBimprimirdepActionPerformed

    private void jBatualizardepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBatualizardepActionPerformed
// TODO add your handling code here:
        int linhaSelecionada = jTlistardep.getSelectedRow();

        if (linhaSelecionada != -1) {
            try {
                int id = (int) jTlistardep.getValueAt(linhaSelecionada, 0);
                String nome = (String) jTlistardep.getValueAt(linhaSelecionada, 1);
                int andar = (int) jTlistardep.getValueAt(linhaSelecionada, 2);

                AltDep ad = new AltDep(id, nome, andar);
                ad.setVisible(true);
                this.dispose();
            } catch (ClassCastException e) {
                JOptionPane.showMessageDialog(this, "Erro ao converter valores da tabela. Verifique os tipos de dados!");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Selecione uma linha para atualizar!");
        }

    }//GEN-LAST:event_jBatualizardepActionPerformed

    private void jBhome2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBhome2ActionPerformed
        // TODO add your handling code here:
        Home home = new Home();
        home.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jBhome2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListarDep.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListarDep.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListarDep.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListarDep.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListarDep().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBatualizardep;
    private javax.swing.JButton jBdeletardep;
    private javax.swing.JButton jBhome2;
    private javax.swing.JButton jBimprimirdep;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTable jTlistardep;
    // End of variables declaration//GEN-END:variables
}
